# Basic Conversions

In [20]:
# imports
import xarray

import numpy as np
from scipy import stats

from matplotlib import pyplot as plt
import seaborn as sns

import pandas

from gsw import conversions, density

# Load up some Spray data

In [2]:
datafile = 'CUGN_line_90.nc'
ds = xarray.load_dataset(datafile)

In [9]:
t_surface = ds.temperature.data[0,:]
s_surface = ds.salinity.data[0,:]
o_surface = ds.doxy.data[0,:]

In [10]:
gd = np.isfinite(t_surface) & np.isfinite(s_surface) & np.isfinite(o_surface)

In [11]:
df_s = pandas.DataFrame()
df_s['Temp'] = t_surface[gd]
df_s['S'] = s_surface[gd]
df_s['O'] = o_surface[gd]

# Pressure

In [7]:
depths = -1*np.arange(10, 510, 10.)

In [12]:
lat = 33.
lon = -117.
ps = conversions.p_from_z(depths, lat)
ps

array([ 10.07123594,  20.14296442,  30.21518535,  40.28789866,
        50.36110426,  60.43480207,  70.50899202,  80.58367401,
        90.65884798, 100.73451384, 110.8106715 , 120.88732089,
       130.96446193, 141.04209454, 151.12021862, 161.19883412,
       171.27794093, 181.35753898, 191.4376282 , 201.51820849,
       211.59927979, 221.680842  , 231.76289504, 241.84543884,
       251.92847332, 262.01199838, 272.09601396, 282.18051997,
       292.26551633, 302.35100295, 312.43697977, 322.52344668,
       332.61040362, 342.69785051, 352.78578726, 362.87421378,
       372.96313001, 383.05253585, 393.14243123, 403.23281607,
       413.32369028, 423.41505378, 433.5069065 , 443.59924834,
       453.69207923, 463.78539909, 473.87920784, 483.97350539,
       494.06829166, 504.16356657])

# Absolute Salinity

In [15]:
SP = ds.salinity.data[0,:]
SA = conversions.SA_from_SP(df_s.S.values, ps[0], lon, lat)
SA

array([33.52390461, 33.52231532, 33.51102584, ..., 32.95951189,
       33.01864566, 33.04357405])

# Conservative Temperature

In [17]:
CT = conversions.CT_from_t(SA, df_s.Temp.values, ps[0])
CT

array([16.24946162, 16.21498956, 16.15802432, ..., 14.46099193,
       14.34062763, 14.2920515 ])

In [19]:
CT - df_s.Temp.values

array([0.03173435, 0.03168956, 0.0318425 , ..., 0.04099193, 0.03922763,
       0.03849595])

# Potential Density

In [22]:
sigma0 = density.sigma0(SA, CT)
sigma0

array([24.44682892, 24.45345253, 24.45780154, ..., 24.40823388,
       24.47848022, 24.50761227])