# Goofy feature in the Lines

In [1]:
# imports
import numpy as np
from siosandbox.cugn import io as cugn_io

# Line 90

# Load

In [3]:
line = '90'
items = cugn_io.load_line(line)
ds = items['ds']

# Find em

In [4]:
xkey = 'SA'
ykey = 'CT'
variable = 'doxy'
#
gd = np.isfinite(ds[xkey]) & np.isfinite(ds[ykey]) & np.isfinite(ds[variable])

In [7]:
bad = (ds[xkey] > 34.) & (ds[ykey] > 16.)

# Examine

In [17]:
in_bool = gd & bad
all_iz, all_ip = np.where(gd & bad)

In [11]:
all_iz

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10])

In [12]:
all_ip

array([39244, 39245, 39246, 39247, 49890, 49891, 49892, 49893, 49894,
       49895, 49896, 49897, 49898, 49899, 49900, 49890, 49891, 49892,
       49893, 49894, 49895, 49896, 49897, 49898, 49899, 49900, 49890,
       49891, 49892, 49893, 49894, 49895, 49896, 49897, 49898, 49899,
       49900, 49890, 49891, 49892, 49893, 49894, 49895, 49896, 49897,
       49898, 49899, 49900, 49890, 49891, 49892, 49893, 49894, 49895,
       49896, 49897, 49898, 49899, 49900, 49890, 49891, 49892, 49893,
       49894, 49895, 49896, 49897, 49898, 49899, 49900, 49890, 49891,
       49892, 49893, 49894, 49895, 49896, 49897, 49898, 49899, 49900,
       49890, 49891, 49892, 49893, 49894, 49895, 49896, 49897, 49898,
       49899, 49900, 49890, 49891, 49892, 49893, 49894, 49895, 49896,
       49897, 49898, 49899, 49900, 49890, 49891, 49892, 49893, 49894,
       49895, 49896, 49897, 49898, 49899, 49900, 49893, 49894, 49895,
       49896])

# Mission

In [15]:
ds.mission[all_ip]

<xarray.DataArray 'mission' (profile: 118)>
array([50, 50, 50, 50, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63],
      dtype=int32)
Coordinates:
  * profile  (profile) int32 39244 39245 39246 39247 ... 49893 49894 49895 49896
    lat      (profile) float64 33.15 33.16 33.17 33.18 ... 21.59 21.59 21.59
    lon      (profile) float64 -118.5 -118.5 -118.5 ... -121.1 -121.1 -121.1
    lat_uv   (profile) float64 33.15 33.16 33.16 33.18 ... 21.59 21.59 21.59
    lon_uv   (profile) float64 -118.5 -118.5 -118.5 ... -121.1 -121.1 -121.1
    time     (profile) datetime64[ns] 2018-11-15T01:30:39 ... 2022-04-24T13:3...
    time_uv  (profile) datetime64[ns] 2018-11-15T00:47:22 ... 2022-04-24T13:2...
Attributes:
    comment:    ATTENTION, please use trajectory_index instead. - This datase...
    long_name:  Mission name of each trajectory

In [16]:
ds.mission_name[63]

<xarray.DataArray 'mission_name' ()>
array(b'21B04101', dtype='|S8')
Attributes:
    long_name:  Mission name of each trajectory.
    comment:    Mission name correlates to the variable trajectory_index.

In [20]:
ds.SA.data[in_bool]

array([34.00351113, 34.00981351, 34.0051735 , 34.00040561, 34.38815017,
       34.39703921, 34.40003106, 34.43435617, 34.42796246, 34.43087617,
       34.44437299, 34.45527276, 34.46123007, 34.48579006, 34.47995706,
       34.38619002, 34.39527722, 34.404677  , 34.43091713, 34.4289914 ,
       34.43074968, 34.44305759, 34.45662141, 34.45745868, 34.48616952,
       34.48405046, 34.38704676, 34.39424427, 34.39680176, 34.43105388,
       34.43278932, 34.4296838 , 34.44361299, 34.45526785, 34.46049244,
       34.48466987, 34.48340026, 34.38820761, 34.39446943, 34.39520014,
       34.42887696, 34.43344849, 34.42787223, 34.44182127, 34.44696215,
       34.41894837, 34.46936769, 34.46514781, 34.38406782, 34.38225016,
       34.37905326, 34.35231808, 34.39914803, 34.41631993, 34.37022754,
       34.40303505, 34.32097023, 34.34233463, 34.39411521, 34.37597324,
       34.32767855, 34.30858842, 34.30508298, 34.22687534, 34.26813073,
       34.28065654, 34.2784461 , 34.27784326, 34.27342238, 34.28

In [21]:
ds.lon[all_ip]

<xarray.DataArray 'lon' (profile: 118)>
array([-118.52773  , -118.5045   , -118.483615 , -118.4635475,
       -121.0997325, -121.09956  , -121.0993925, -121.0992525,
       -121.0993975, -121.0989375, -121.0973325, -121.0955325,
       -121.094155 , -121.0922125, -121.0906975, -121.0997325,
       -121.09956  , -121.0993925, -121.0992525, -121.0993975,
       -121.0989375, -121.0973325, -121.0955325, -121.094155 ,
       -121.0922125, -121.0906975, -121.0997325, -121.09956  ,
       -121.0993925, -121.0992525, -121.0993975, -121.0989375,
       -121.0973325, -121.0955325, -121.094155 , -121.0922125,
       -121.0906975, -121.0997325, -121.09956  , -121.0993925,
       -121.0992525, -121.0993975, -121.0989375, -121.0973325,
       -121.0955325, -121.094155 , -121.0922125, -121.0906975,
       -121.0997325, -121.09956  , -121.0993925, -121.0992525,
       -121.0993975, -121.0989375, -121.0973325, -121.0955325,
       -121.094155 , -121.0922125, -121.0906975, -121.0997325,
       -121.09956  , -121.0993925, -121.0992525, -121.0993975,
       -121.0989375, -121.0973325, -121.0955325, -121.094155 ,
       -121.0922125, -121.0906975, -121.0997325, -121.09956  ,
       -121.0993925, -121.0992525, -121.0993975, -121.0989375,
       -121.0973325, -121.0955325, -121.094155 , -121.0922125,
       -121.0906975, -121.0997325, -121.09956  , -121.0993925,
       -121.0992525, -121.0993975, -121.0989375, -121.0973325,
       -121.0955325, -121.094155 , -121.0922125, -121.0906975,
       -121.0997325, -121.09956  , -121.0993925, -121.0992525,
       -121.0993975, -121.0989375, -121.0973325, -121.0955325,
       -121.094155 , -121.0922125, -121.0906975, -121.0997325,
       -121.09956  , -121.0993925, -121.0992525, -121.0993975,
       -121.0989375, -121.0973325, -121.0955325, -121.094155 ,
       -121.0922125, -121.0906975, -121.0992525, -121.0993975,
       -121.0989375, -121.0973325])
Coordinates:
  * profile  (profile) int32 39244 39245 39246 39247 ... 49893 49894 49895 49896
    lat      (profile) float64 33.15 33.16 33.17 33.18 ... 21.59 21.59 21.59
    lon      (profile) float64 -118.5 -118.5 -118.5 ... -121.1 -121.1 -121.1
    lat_uv   (profile) float64 33.15 33.16 33.16 33.18 ... 21.59 21.59 21.59
    lon_uv   (profile) float64 -118.5 -118.5 -118.5 ... -121.1 -121.1 -121.1
    time     (profile) datetime64[ns] 2018-11-15T01:30:39 ... 2022-04-24T13:3...
    time_uv  (profile) datetime64[ns] 2018-11-15T00:47:22 ... 2022-04-24T13:2...
Attributes:
    long_name:              Longitude
    standard_name:          longitude
    units:                  degrees_east
    coverage_content_type:  coordinate
    comment:                The estimated longitude of the midpoint of the pr...

----

# Line 80

In [2]:
line = '80'
items = cugn_io.load_line(line)
ds = items['ds']

In [10]:
gd80 = np.isfinite(ds[xkey]) & np.isfinite(ds[ykey]) & np.isfinite(ds[variable])
bad = (ds[xkey] > 33.7) & (ds[ykey] > 19.)
xkey, ykey, variable

('SA', 'CT', 'doxy')

In [7]:
in_bool = gd & bad
all_iz, all_ip = np.where(gd & bad)
ds.mission[all_ip]

<xarray.DataArray 'mission' (profile: 86)>
array([51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
       51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 52, 52, 52, 52, 52, 52,
       52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 59, 59,
       59, 59, 59, 59, 59, 59, 59, 63, 63, 63, 63, 67, 67, 67, 67, 67, 51,
       52, 52, 52, 67, 67, 67, 67, 67, 67, 56, 56, 56, 56, 67, 67, 67, 67,
       67], dtype=int32)
Coordinates:
  * profile  (profile) int32 39861 39862 39877 39879 ... 53252 53253 53256 53257
    lat      (profile) float64 34.32 34.32 34.29 34.29 ... 33.67 33.64 33.63
    lon      (profile) float64 -120.8 -120.8 -120.7 ... -122.2 -122.2 -122.2
    lat_uv   (profile) float64 34.32 34.32 34.29 34.29 ... 33.67 33.65 33.64
    lon_uv   (profile) float64 -120.8 -120.8 -120.7 ... -122.2 -122.2 -122.2
    time     (profile) datetime64[ns] 2018-08-14T16:49:26 ... 2022-10-01T17:4...
    time_uv  (profile) datetime64[ns] 2018-08-14T16:04:14 ... 2022-10-01T17:0...
Attributes:
    comment:    ATTENTION, please use trajectory_index instead. - This datase...
    long_name:  Mission name of each trajectory

In [8]:
ds.lon[all_ip]

<xarray.DataArray 'lon' (profile: 86)>
array([-120.78666  , -120.7811725, -120.7138325, -120.69985  ,
       -120.6859825, -120.6714   , -120.6611   , -120.6502975,
       -120.63759  , -120.630095 , -120.6249175, -120.6184375,
       -120.6106075, -120.60429  , -120.5956225, -120.58584  ,
       -120.5782625, -120.572015 , -120.5619825, -120.5476525,
       -120.529795 , -120.51296  , -120.4919825, -120.47001  ,
       -120.4506525, -120.4321925, -120.219795 , -120.191565 ,
       -119.782815 , -119.7914375, -119.7995275, -119.8103725,
       -119.8230175, -119.8396125, -119.8613875, -119.88621  ,
       -119.9136125, -119.940885 , -119.97021  , -120.0023325,
       -120.038135 , -120.1770325, -120.21413  , -120.2451125,
       -120.2741325, -120.3060325, -120.341445 , -120.4081475,
       -120.4328875, -119.8640625, -119.8524525, -119.869155 ,
       -119.8469   , -119.8661025, -119.85672  , -119.854005 ,
       -119.8500725, -119.8699475, -119.822125 , -119.8440075,
       -119.87256  , -119.90123  , -122.157945 , -122.17871  ,
       -122.2013   , -122.2202175, -122.23453  , -120.5619825,
       -119.88621  , -119.9136125, -119.940885 , -122.13948  ,
       -122.157945 , -122.17871  , -122.2013   , -122.2202175,
       -122.23453  , -123.6500575, -123.6783275, -123.7068675,
       -123.75807  , -122.1000025, -122.13948  , -122.157945 ,
       -122.2202175, -122.23453  ])
Coordinates:
  * profile  (profile) int32 39861 39862 39877 39879 ... 53252 53253 53256 53257
    lat      (profile) float64 34.32 34.32 34.29 34.29 ... 33.67 33.64 33.63
    lon      (profile) float64 -120.8 -120.8 -120.7 ... -122.2 -122.2 -122.2
    lat_uv   (profile) float64 34.32 34.32 34.29 34.29 ... 33.67 33.65 33.64
    lon_uv   (profile) float64 -120.8 -120.8 -120.7 ... -122.2 -122.2 -122.2
    time     (profile) datetime64[ns] 2018-08-14T16:49:26 ... 2022-10-01T17:4...
    time_uv  (profile) datetime64[ns] 2018-08-14T16:04:14 ... 2022-10-01T17:0...
Attributes:
    long_name:              Longitude
    standard_name:          longitude
    units:                  degrees_east
    coverage_content_type:  coordinate
    comment:                The estimated longitude of the midpoint of the pr...