# Goofy feature in Line 90

In [5]:
# imports
import numpy as np
from siosandbox.cugn import io as cugn_io

# Load

In [3]:
line = '90'
items = cugn_io.load_line(line)
ds = items['ds']

# Find em

In [6]:
xkey = 'SA'
ykey = 'CT'
variable = 'doxy'
#
gd = np.isfinite(ds[xkey]) & np.isfinite(ds[ykey]) & np.isfinite(ds[variable])

In [7]:
bad = (ds[xkey] > 34.) & (ds[ykey] > 16.)

# Examine

In [17]:
in_bool = gd & bad
all_iz, all_ip = np.where(gd & bad)

In [11]:
all_iz

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10])

In [12]:
all_ip

array([39244, 39245, 39246, 39247, 49890, 49891, 49892, 49893, 49894,
       49895, 49896, 49897, 49898, 49899, 49900, 49890, 49891, 49892,
       49893, 49894, 49895, 49896, 49897, 49898, 49899, 49900, 49890,
       49891, 49892, 49893, 49894, 49895, 49896, 49897, 49898, 49899,
       49900, 49890, 49891, 49892, 49893, 49894, 49895, 49896, 49897,
       49898, 49899, 49900, 49890, 49891, 49892, 49893, 49894, 49895,
       49896, 49897, 49898, 49899, 49900, 49890, 49891, 49892, 49893,
       49894, 49895, 49896, 49897, 49898, 49899, 49900, 49890, 49891,
       49892, 49893, 49894, 49895, 49896, 49897, 49898, 49899, 49900,
       49890, 49891, 49892, 49893, 49894, 49895, 49896, 49897, 49898,
       49899, 49900, 49890, 49891, 49892, 49893, 49894, 49895, 49896,
       49897, 49898, 49899, 49900, 49890, 49891, 49892, 49893, 49894,
       49895, 49896, 49897, 49898, 49899, 49900, 49893, 49894, 49895,
       49896])

# Mission

In [15]:
ds.mission[all_ip]

<xarray.DataArray 'mission' (profile: 118)>
array([50, 50, 50, 50, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63],
      dtype=int32)
Coordinates:
  * profile  (profile) int32 39244 39245 39246 39247 ... 49893 49894 49895 49896
    lat      (profile) float64 33.15 33.16 33.17 33.18 ... 21.59 21.59 21.59
    lon      (profile) float64 -118.5 -118.5 -118.5 ... -121.1 -121.1 -121.1
    lat_uv   (profile) float64 33.15 33.16 33.16 33.18 ... 21.59 21.59 21.59
    lon_uv   (profile) float64 -118.5 -118.5 -118.5 ... -121.1 -121.1 -121.1
    time     (profile) datetime64[ns] 2018-11-15T01:30:39 ... 2022-04-24T13:3...
    time_uv  (profile) datetime64[ns] 2018-11-15T00:47:22 ... 2022-04-24T13:2...
Attributes:
    comment:    ATTENTION, please use trajectory_index instead. - This datase...
    long_name:  Mission name of each trajectory

In [16]:
ds.mission_name[63]

<xarray.DataArray 'mission_name' ()>
array(b'21B04101', dtype='|S8')
Attributes:
    long_name:  Mission name of each trajectory.
    comment:    Mission name correlates to the variable trajectory_index.

In [20]:
ds.SA.data[in_bool]

array([34.00351113, 34.00981351, 34.0051735 , 34.00040561, 34.38815017,
       34.39703921, 34.40003106, 34.43435617, 34.42796246, 34.43087617,
       34.44437299, 34.45527276, 34.46123007, 34.48579006, 34.47995706,
       34.38619002, 34.39527722, 34.404677  , 34.43091713, 34.4289914 ,
       34.43074968, 34.44305759, 34.45662141, 34.45745868, 34.48616952,
       34.48405046, 34.38704676, 34.39424427, 34.39680176, 34.43105388,
       34.43278932, 34.4296838 , 34.44361299, 34.45526785, 34.46049244,
       34.48466987, 34.48340026, 34.38820761, 34.39446943, 34.39520014,
       34.42887696, 34.43344849, 34.42787223, 34.44182127, 34.44696215,
       34.41894837, 34.46936769, 34.46514781, 34.38406782, 34.38225016,
       34.37905326, 34.35231808, 34.39914803, 34.41631993, 34.37022754,
       34.40303505, 34.32097023, 34.34233463, 34.39411521, 34.37597324,
       34.32767855, 34.30858842, 34.30508298, 34.22687534, 34.26813073,
       34.28065654, 34.2784461 , 34.27784326, 34.27342238, 34.28

In [21]:
ds.lon[all_ip]

<xarray.DataArray 'lon' (profile: 118)>
array([-118.52773  , -118.5045   , -118.483615 , -118.4635475,
       -121.0997325, -121.09956  , -121.0993925, -121.0992525,
       -121.0993975, -121.0989375, -121.0973325, -121.0955325,
       -121.094155 , -121.0922125, -121.0906975, -121.0997325,
       -121.09956  , -121.0993925, -121.0992525, -121.0993975,
       -121.0989375, -121.0973325, -121.0955325, -121.094155 ,
       -121.0922125, -121.0906975, -121.0997325, -121.09956  ,
       -121.0993925, -121.0992525, -121.0993975, -121.0989375,
       -121.0973325, -121.0955325, -121.094155 , -121.0922125,
       -121.0906975, -121.0997325, -121.09956  , -121.0993925,
       -121.0992525, -121.0993975, -121.0989375, -121.0973325,
       -121.0955325, -121.094155 , -121.0922125, -121.0906975,
       -121.0997325, -121.09956  , -121.0993925, -121.0992525,
       -121.0993975, -121.0989375, -121.0973325, -121.0955325,
       -121.094155 , -121.0922125, -121.0906975, -121.0997325,
       -121.09956  , -121.0993925, -121.0992525, -121.0993975,
       -121.0989375, -121.0973325, -121.0955325, -121.094155 ,
       -121.0922125, -121.0906975, -121.0997325, -121.09956  ,
       -121.0993925, -121.0992525, -121.0993975, -121.0989375,
       -121.0973325, -121.0955325, -121.094155 , -121.0922125,
       -121.0906975, -121.0997325, -121.09956  , -121.0993925,
       -121.0992525, -121.0993975, -121.0989375, -121.0973325,
       -121.0955325, -121.094155 , -121.0922125, -121.0906975,
       -121.0997325, -121.09956  , -121.0993925, -121.0992525,
       -121.0993975, -121.0989375, -121.0973325, -121.0955325,
       -121.094155 , -121.0922125, -121.0906975, -121.0997325,
       -121.09956  , -121.0993925, -121.0992525, -121.0993975,
       -121.0989375, -121.0973325, -121.0955325, -121.094155 ,
       -121.0922125, -121.0906975, -121.0992525, -121.0993975,
       -121.0989375, -121.0973325])
Coordinates:
  * profile  (profile) int32 39244 39245 39246 39247 ... 49893 49894 49895 49896
    lat      (profile) float64 33.15 33.16 33.17 33.18 ... 21.59 21.59 21.59
    lon      (profile) float64 -118.5 -118.5 -118.5 ... -121.1 -121.1 -121.1
    lat_uv   (profile) float64 33.15 33.16 33.16 33.18 ... 21.59 21.59 21.59
    lon_uv   (profile) float64 -118.5 -118.5 -118.5 ... -121.1 -121.1 -121.1
    time     (profile) datetime64[ns] 2018-11-15T01:30:39 ... 2022-04-24T13:3...
    time_uv  (profile) datetime64[ns] 2018-11-15T00:47:22 ... 2022-04-24T13:2...
Attributes:
    long_name:              Longitude
    standard_name:          longitude
    units:                  degrees_east
    coverage_content_type:  coordinate
    comment:                The estimated longitude of the midpoint of the pr...